---
services:
  web:
    container_name: cset-web
    hostname: web
    image: ghcr.io/cisagov/cset/web:latest
    build:
      context: CSETWebNg
    restart: unless-stopped
    stdin_open: true
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 4200:80
      - 443:443
  api:
    container_name: cset-api
    hostname: api
    image: ghcr.io/cisagov/cset/api:latest
    build:
      context: CSETWebApi
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - sqlserver
  sqlserver:
    container_name: cset-mssql
    hostname: mssql
    image: "mcr.microsoft.com/mssql/server:2022-CU13-ubuntu-22.04"
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./backup:/var/opt/mssql/backup
      - ./DatabaseScripts:/var/opt/mssql/scripts

volumes:
  mssql_data:
