---
services:
  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: csetweb
      POSTGRES_USER: cset
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - cset-network

networks:
  cset-network:
    driver: bridge

volumes:
  postgres-data:
