name: Docker Build

on:
  pull_request:
    branches:
      - develop
      - release/*
  push:
    branches:
      - release/*

env:
  IMAGE: ${{ secrets.IMAGE }}
  PAT: ${{ secrets.PAT }}

jobs:
  build-api:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    defaults:
      run:
        working-directory: ./CSETWebApi
    steps:
      - uses: actions/checkout@v5

      - name: Registry login
        run: echo $PAT | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Pull Docker Image
        run: docker pull $IMAGE/api:latest || true

      - name: Tag Docker Image
        run: docker build -f Dockerfile . --tag $IMAGE/api:latest --cache-from $IMAGE/api:latest

      - name: Push Docker Image
        run: docker push $IMAGE/api:latest
  build-web:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    defaults:
      run:
        working-directory: ./CSETWebNg
    steps:
      - uses: actions/checkout@v5

      - name: Registry login
        run: echo $PAT | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Pull Docker Image
        run: docker pull $IMAGE/web:latest || true

      - name: Tag Docker Image
        run: docker build -f Dockerfile . --tag $IMAGE/web:latest --cache-from $IMAGE/web:latest

      - name: Push Docker Image
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: docker push $IMAGE/web:latest
  dependabot-build:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v5
      
      - name: Basic build test (API)
        working-directory: ./CSETWebApi
        run: docker build -f Dockerfile . --tag test-api:latest
        
      - name: Basic build test (Web)
        working-directory: ./CSETWebNg
        run: docker build -f Dockerfile . --tag test-web:latest
